### ISSUE TITLE
Feature request: Support multiple languages

### ISSUE THREAD

**Issue by steve1977** [RandomNinjaAtk/docker-sabnzbd-extended#15]
Currently, the script only supports one default language:

-e ReqauireLanguage=true
-e VIDEO_LANG=eng

I have some German movies, which do not have English sub-titles either. So, ideally I could set the required language to "English or German".

Possible?

Thanks in advance for considering!

**Comment by RandomNinjaAtk** [comment]
Should be enabled in the latest update

**Comment by RandomNinjaAtk** [comment]
I believe this is resolved....
