### ISSUE TITLE
A Few Spelling Errors

### ISSUE THREAD

**Issue by EthanBezz** [RandomNinjaAtk/docker-sabnzbd-extended#2]
### 1. UPDATE is spelt as "UDPATE"
In "Dockerfile"
`ENV UDPATE_SMA FALSE`
should be
`ENV UPDATE_SMA FALSE`

In "30-script-update.bash"
`if [[ "${UDPATE_SMA}" == "TRUE" ]]; then`
should be
`if [[ "${UPDATE_SMA}" == "TRUE" ]]; then`

### 2. storage is spelt as "stroage" and there are some double slashes

In "31-path-setup.bash"
```
# Create downloads incomplete directory
if [ ! -d "/stroage/downloads/sabnzbd/incomplete" ]; then
	mkdir -p "/stroage/downloads/sabnzbd/incomplete"
	chmod 0777 "/stroage/downloads/sabnzbd/incomplete"
fi

# Create downloads complete directory
if [ ! -d "/stroage//downloads/sabnzbd/complete" ]; then
	mkdir -p "/stroage//downloads/sabnzbd/complete"
	chmod 0777 "/stroage//downloads/sabnzbd/complete"
fi
```
should be
```
# Create downloads incomplete directory
if [ ! -d "/storage/downloads/sabnzbd/incomplete" ]; then
	mkdir -p "/storage/downloads/sabnzbd/incomplete"
	chmod 0777 "/storage/downloads/sabnzbd/incomplete"
fi

# Create downloads complete directory
if [ ! -d "/storage/downloads/sabnzbd/complete" ]; then
	mkdir -p "/storage/downloads/sabnzbd/complete"
	chmod 0777 "/storage/downloads/sabnzbd/complete"
fi
```
This is my first time creating an issue on GitHub so I apologise in advance for any weirdness

**Comment by RandomNinjaAtk** [comment]
This should be fixed.... The image should be building, strange I didn't pick up on this because I rebuilt my setup last night. I swear sometimes, they keys don't always input as I tell them too...

Let me know if that resolves everything...

**Comment by EthanBezz** [comment]
I just pulled the new image and everything looks good. Thanks.

> I swear sometimes, the keys don't always input as I tell them too...

I'm always finding myself typing words with 2 of the letters swapped around. it happens to the best of us I guess.
